### ISSUE TITLE
[RA1] Briefing text too slow and press Esc to instantly display all of the briefing text not working.

### ISSUE THREAD

**Issue by Allen262** [TheAssemblyArmada/Vanilla-Conquer#698] opened 2021-10-26 21:33 UTC
VRA "types" the briefing text slower than 3.03 and Pressing Esc should instantly display all of the briefing text instead of typing it. This dose not work VRA. Tested on R698 B7B8B62

**Comment by OmniBlade** [comment] 2021-11-17 22:30
Probably related to #642

**Comment by OmniBlade** [comment] 2021-11-17 22:45
Also probably a duplicate of #531

**Comment by Allen262** [comment] 2021-11-17 22:56
Windows 10.

**Closed as completed** 2021-12-08 20:52 UTC
Labels: bug, duplicate
